# Generated by Django 3.1.4 on 2021-01-18 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20210118_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.exam'),
        ),
    ]
