# Generated by Django 3.1.4 on 2021-01-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20210118_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='persentage',
            field=models.IntegerField(null=True, verbose_name='Persentase'),
        ),
    ]
