# Generated by Django 3.1.4 on 2021-01-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_score_persentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='passed_test',
            field=models.BooleanField(default=False, verbose_name='Lulus'),
        ),
    ]
