# Generated by Django 3.1.4 on 2021-01-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_score_passed_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.CharField(default=0, max_length=1, verbose_name='Durasi Ujian'),
        ),
    ]
