# Generated by Django 3.1.4 on 2021-01-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20210124_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='passed_test',
        ),
    ]
