# Generated by Django 3.1.4 on 2021-03-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
