---
deployment:
  tasks:
    - export DEPLOYPATH=/home/smktelko/primaseru/
    # - /bin/cp -rf * $DEPLOYPATH
    # - /bin/cp -rf ppdb $DEPLOYPATH
    - /bin/cp -rf dashboard $DEPLOYPATH
    - /bin/cp -rf exam $DEPLOYPATH
    - /bin/cp -rf primaseru $DEPLOYPATH
    - /bin/cp -rf users $DEPLOYPATH
