---
deployment:
  tasks:
    - export DEPLOYPATH=/home/smktelko/primaseru/
    - /bin/cp -R dashboard $DEPLOYPATH
    - /bin/cp -R db.sqlite3 $DEPLOYPATH
    - /bin/cp -R exam $DEPLOYPATH
    - /bin/cp -R manage.py $DEPLOYPATH
    - /bin/cp -R ppdb $DEPLOYPATH
    - /bin/cp -R media $DEPLOYPATH
    - /bin/cp -R primaseru $DEPLOYPATH
    - /bin/cp -R users $DEPLOYPATH
    - /bin/cp -R requirements.txt $DEPLOYPATH
