# Generated by Django 3.1.4 on 2021-03-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstatus',
            old_name='status',
            new_name='accepted',
        ),
    ]
