# Generated by Django 3.1.4 on 2021-03-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210311_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatus',
            name='major',
            field=models.CharField(choices=[(None, '=Pilih='), ('TKJ', 'Teknik Komputer dan Jaringan'), ('TJAT', 'Teknik Jaringan Akses dan Telekomunikasi'), ('MM', 'Multimedia')], max_length=4, verbose_name='Diterima dijurusan'),
        ),
    ]
