# Generated by Django 3.1.4 on 2021-03-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210317_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatus',
            name='major',
            field=models.CharField(blank=True, choices=[(None, '=Pilih='), ('TKJ', 'Teknik Komputer dan Jaringan'), ('TJAT', 'Teknik Jaringan Akses dan Telekomunikasi'), ('MM', 'Multimedia')], max_length=4, null=True, verbose_name='Diterima dijurusan'),
        ),
    ]
