# Generated by Django 3.1.4 on 2020-12-22 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_regis', models.PositiveIntegerField(verbose_name='No. Pendaftaran')),
                ('sex', models.CharField(choices=[(None, '=Pilih='), ('L', 'Laki - Laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('religion', models.CharField(choices=[(None, '=Pilih='), ('ISL', 'Islam'), ('KRS', 'Kristen'), ('KTL', 'Katolik'), ('HND', 'Hindu'), ('BDH', 'Budha'), ('KHC', 'Kong Hu Cu')], max_length=3, verbose_name='Agama')),
                ('city_born', models.CharField(help_text='Contoh: Kabupaten Bandung', max_length=100, verbose_name='Tempat Lahir')),
                ('date_born', models.DateField(verbose_name='Tanggal Lahir')),
                ('achievement', models.CharField(blank=True, max_length=120, null=True, verbose_name='Prestasi Akademik/Non Akademik')),
                ('nisn', models.PositiveIntegerField(verbose_name='NISN')),
                ('nik', models.PositiveIntegerField(unique=True, verbose_name='Nomor Induk Kependudukan (NIK)')),
                ('no_kk', models.PositiveIntegerField(verbose_name='Nomor Kartu Keluarga (KK)')),
                ('address_kk', models.TextField(verbose_name='Alamat KK')),
                ('city', models.CharField(help_text='Contoh: Kabupaten Bandung', max_length=120, verbose_name='Kota/Kabupaten')),
                ('kecamatan', models.CharField(max_length=120)),
                ('kelurahan', models.CharField(max_length=120)),
                ('dusun', models.CharField(max_length=120)),
                ('rt_rw', models.CharField(max_length=8, verbose_name='RT/RW')),
                ('real_address', models.TextField(verbose_name='Alamat Sekarang')),
                ('resident', models.CharField(max_length=50, verbose_name='Tempat Tinggal')),
                ('transport', models.CharField(max_length=50, verbose_name='Alat Transportasi')),
                ('handpone', models.PositiveIntegerField(verbose_name='No. HP')),
                ('email', models.EmailField(max_length=254)),
                ('social_media', models.CharField(max_length=100, verbose_name='Akun Sosial Media')),
                ('school_origin', models.CharField(max_length=120, verbose_name='Asal Sekolah')),
                ('npsn_school_origin', models.PositiveIntegerField(verbose_name='Nomor NPSN Sekolah Asal')),
                ('medic_record', models.TextField(blank=True, null=True, verbose_name='Riwayat Kesehatan')),
                ('blood_type', models.CharField(choices=[(None, '=Pilih='), ('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O'), ('0', 'Tidak Tahu')], max_length=2, verbose_name='Golongan Darah')),
                ('in_medicine', models.CharField(blank=True, max_length=120, null=True, verbose_name='Dalam Pengobatan')),
                ('private_doctor', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nama Dokter Keluarga')),
                ('phone_doctor', models.PositiveIntegerField(blank=True, null=True, verbose_name='No Telepon Dokter')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGuardianProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nama Lengkap')),
                ('city_born', models.CharField(help_text='Contoh: Kabupaten Bandung', max_length=120, verbose_name='Kota/Kabupaten Kelahiran')),
                ('date_born', models.DateField(verbose_name='Tanggal Lahir')),
                ('nik', models.PositiveIntegerField(unique=True, verbose_name='Nomor Induk Kependudukan (NIK)')),
                ('education', models.CharField(choices=[(None, '=Pilih='), ('SD', 'SD'), ('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=4, verbose_name='Pendidikan Terakhir')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pekerjaan')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Penghasilan')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.PositiveIntegerField(verbose_name='No. HP')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default_photo.png', null=True, upload_to='profile_pics', verbose_name='Photo')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MotherStudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nama Lengkap')),
                ('city_born', models.CharField(help_text='Contoh: Kabupaten Bandung', max_length=120, verbose_name='Kota/Kabupaten Kelahiran')),
                ('date_born', models.DateField(verbose_name='Tanggal Lahir')),
                ('nik', models.PositiveIntegerField(unique=True, verbose_name='Nomor Induk Kependudukan (NIK)')),
                ('education', models.CharField(choices=[(None, '=Pilih='), ('SD', 'SD'), ('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=4, verbose_name='Pendidikan Terakhir')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pekerjaan')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Penghasilan')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.PositiveIntegerField(verbose_name='No. HP')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MajorStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_major', models.CharField(choices=[(None, '=Pilih='), ('TKJ', 'Teknik Komputer dan Jaringan'), ('TJAT', 'Teknik Jaringan Akses dan Telekomunikasi'), ('MM', 'Multimedia')], max_length=4, verbose_name='Pilihan Jurusan Pertama')),
                ('second_major', models.CharField(choices=[(None, '=Pilih='), ('TKJ', 'Teknik Komputer dan Jaringan'), ('TJAT', 'Teknik Jaringan Akses dan Telekomunikasi'), ('MM', 'Multimedia')], max_length=4, verbose_name='Pilihan Jurusan Kedua')),
                ('info', models.CharField(max_length=120, verbose_name='Info Primaseru (PPDB)')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FatherStudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nama Lengkap')),
                ('city_born', models.CharField(help_text='Contoh: Kabupaten Bandung', max_length=120, verbose_name='Kota/Kabupaten Kelahiran')),
                ('date_born', models.DateField(verbose_name='Tanggal Lahir')),
                ('nik', models.PositiveIntegerField(unique=True, verbose_name='Nomor Induk Kependudukan (NIK)')),
                ('education', models.CharField(choices=[(None, '=Pilih='), ('SD', 'SD'), ('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=4, verbose_name='Pendidikan Terakhir')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pekerjaan')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Penghasilan')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.PositiveIntegerField(verbose_name='No. HP')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
