# Generated by Django 3.1.4 on 2020-12-31 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import primaseru.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('no_regis', models.PositiveIntegerField(help_text='Bisa Konfirmasi Ke Bagian Pendaftaran, Contoh : 221321', null=True, unique=True, verbose_name='No. Pendaftaran')),
                ('sex', models.CharField(choices=[(None, '=Pilih='), ('L', 'Laki - Laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('religion', models.CharField(choices=[(None, '=Pilih='), ('ISL', 'Islam'), ('KRS', 'Kristen'), ('KTL', 'Katolik'), ('HND', 'Hindu'), ('BDH', 'Budha'), ('KHC', 'Kong Hu Cu')], max_length=3, verbose_name='Agama')),
                ('handpone', models.PositiveIntegerField(null=True, verbose_name='No. HP')),
                ('city_born', models.CharField(help_text='Contoh: Kabupaten Bandung', max_length=100, verbose_name='Tempat Lahir')),
                ('date_born', models.DateField(null=True, verbose_name='Tanggal Lahir')),
                ('social_media', models.CharField(help_text='Seperti Alamat Twitter, IG, atau FB', max_length=100, verbose_name='Akun Sosial Media')),
                ('achievement', models.TextField(blank=True, help_text='Contoh : Juara 3 Lomba Basket Antar SMA Tingkat Kabupaten tahun 2018 atau Juara 3 Pencak Silat Ditingkat Kabupaten tahun 2018 ', max_length=120, null=True, verbose_name='Prestasi Akademik/Non Akademik')),
                ('nisn', models.PositiveIntegerField(help_text='Isi berdasarkan NISN yang diberikan SMP Asal', null=True, unique=True, verbose_name='NISN')),
                ('nik', models.PositiveIntegerField(help_text='Bisa dicek di Kartu Keluarga', null=True, unique=True, verbose_name='Nomor Induk Kependudukan (NIK)')),
                ('no_kk', models.PositiveIntegerField(help_text='Diisi Berdasarkan Kartu Keluarga', null=True, verbose_name='Nomor Kartu Keluarga (KK)')),
                ('address_kk', models.TextField(help_text='Contoh: Jalan Radio Palasari', null=True, verbose_name='Alamat Kartu Keluarga (KK)')),
                ('city', models.CharField(help_text='Contoh: Kabupaten Bandung', max_length=120, verbose_name='Kota/Kabupaten')),
                ('kecamatan', models.CharField(help_text='Contoh : Kecamatan Dayeuhkolot', max_length=120)),
                ('kelurahan', models.CharField(help_text='Contoh : Desa Citeureup', max_length=120)),
                ('dusun', models.CharField(help_text='Jika tidak tahu ada maka diisi dengan -', max_length=120)),
                ('rt_rw', models.CharField(help_text='Contoh: 06/02', max_length=8, verbose_name='RT/RW')),
                ('real_address', models.TextField(help_text='Contoh : Jalan Bojongsoang', verbose_name='Alamat Sekarang')),
                ('resident', models.CharField(help_text='Contoh: Rumah Pribadi, Kost, Rumah Keluarga (Keluarga Besar).', max_length=50, verbose_name='Tempat Tinggal')),
                ('transport', models.CharField(help_text='Contoh: Jalan Kaki, Motor, Ojek Online, Sepeda, Mobil, Angkot.', max_length=50, verbose_name='Alat Transportasi')),
                ('school_origin', models.CharField(help_text='Isilah sesuai dengan asal sekolah Anda dan dituliskan seperti contoh berikut : SMP Telkom Bandung ', max_length=120, verbose_name='Asal Sekolah')),
                ('npsn_school_origin', models.PositiveIntegerField(help_text="Bisa Cek <a href='https://referensi.data.kemdikbud.go.id/index11.php' target='_blank'><b>Disini</b></a>", null=True, verbose_name='Nomor NPSN Sekolah Asal')),
                ('medic_record', models.TextField(blank=True, help_text='Jika pernah mempunyai penyakit, silahkan ditulis disini', null=True, verbose_name='Riwayat Kesehatan')),
                ('blood_type', models.CharField(choices=[(None, '=Pilih='), ('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O'), ('0', 'Tidak Tahu')], max_length=2, verbose_name='Golongan Darah')),
                ('in_medicine', models.CharField(blank=True, max_length=120, null=True, verbose_name='Dalam Pengobatan')),
                ('private_doctor', models.CharField(blank=True, help_text='Jika kamu mempunyai dokter keluarga, silahkan input disini', max_length=120, null=True, verbose_name='Nama Dokter Keluarga')),
                ('phone_doctor', models.PositiveIntegerField(blank=True, help_text='Isi jika memiliki dokter keluarga dan atau dalam masa penyambuhan penyakit', null=True, verbose_name='No Telepon Dokter')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGuardianProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=120, verbose_name='Nama Lengkap')),
                ('city_born', models.CharField(help_text='Contoh pengisian tempat lahir: Kab bandung', max_length=120, verbose_name='Kota/Kabupaten Kelahiran')),
                ('date_born', models.DateField(null=True, verbose_name='Tanggal Lahir')),
                ('nik', models.PositiveIntegerField(help_text='Diisi berdasarkan Kartu Keluarga', null=True, verbose_name='Nomor Induk Kependudukan (NIK)')),
                ('education', models.CharField(choices=[(None, '=Pilih='), ('SD', 'SD'), ('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=4, verbose_name='Pendidikan Terakhir')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pekerjaan')),
                ('salary', models.PositiveIntegerField(blank=True, help_text='Diisi dengan angka', null=True, verbose_name='Penghasilan')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.PositiveIntegerField(null=True, verbose_name='No. HP')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('msg', models.CharField(blank=True, max_length=120, null=True, verbose_name='Pesan')),
                ('ra_sem_1', models.FileField(upload_to=primaseru.models.user_directory_path, verbose_name='Rapor Semester 1')),
                ('ra_sem_2', models.FileField(upload_to=primaseru.models.user_directory_path, verbose_name='Rapor Semester 2')),
                ('ra_sem_3', models.FileField(upload_to=primaseru.models.user_directory_path, verbose_name='Rapor Semester 3')),
                ('ra_sem_4', models.FileField(upload_to=primaseru.models.user_directory_path, verbose_name='Rapor Semester 4')),
                ('ra_sem_5', models.FileField(blank=True, null=True, upload_to=primaseru.models.user_directory_path, verbose_name='Rapor Semester 5')),
                ('color_blind_cert', models.FileField(upload_to=primaseru.models.user_directory_path, verbose_name='Semester Keterangan Tidak Buta Warna')),
                ('healty_cert', models.FileField(upload_to=primaseru.models.user_directory_path, verbose_name='Surat Keterangan Sehat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_photo.png', upload_to='profile_pics', verbose_name='Photo')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MotherStudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=120, verbose_name='Nama Lengkap')),
                ('city_born', models.CharField(help_text='Contoh pengisian tempat lahir: Kab bandung', max_length=120, verbose_name='Kota/Kabupaten Kelahiran')),
                ('date_born', models.DateField(null=True, verbose_name='Tanggal Lahir')),
                ('nik', models.PositiveIntegerField(help_text='Diisi berdasarkan Kartu Keluarga', null=True, verbose_name='Nomor Induk Kependudukan (NIK)')),
                ('education', models.CharField(choices=[(None, '=Pilih='), ('SD', 'SD'), ('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=4, verbose_name='Pendidikan Terakhir')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pekerjaan')),
                ('salary', models.PositiveIntegerField(blank=True, help_text='Diisi dengan angka', null=True, verbose_name='Penghasilan')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.PositiveIntegerField(null=True, verbose_name='No. HP')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MajorStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('first_major', models.CharField(choices=[(None, '=Pilih='), ('TKJ', 'Teknik Komputer dan Jaringan'), ('TJAT', 'Teknik Jaringan Akses dan Telekomunikasi'), ('MM', 'Multimedia')], max_length=4, verbose_name='Pilihan Jurusan Pertama')),
                ('second_major', models.CharField(choices=[(None, '=Pilih='), ('TKJ', 'Teknik Komputer dan Jaringan'), ('TJAT', 'Teknik Jaringan Akses dan Telekomunikasi'), ('MM', 'Multimedia')], max_length=4, verbose_name='Pilihan Jurusan Kedua')),
                ('info', models.CharField(help_text='Tuliskan Darimana Kamu Mendapatkan Info Tentang Primaseru.', max_length=120, verbose_name='Info Primaseru (PPDB)')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FatherStudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=120, verbose_name='Nama Lengkap')),
                ('city_born', models.CharField(help_text='Contoh pengisian tempat lahir: Kab bandung', max_length=120, verbose_name='Kota/Kabupaten Kelahiran')),
                ('date_born', models.DateField(null=True, verbose_name='Tanggal Lahir')),
                ('nik', models.PositiveIntegerField(help_text='Diisi berdasarkan Kartu Keluarga', null=True, verbose_name='Nomor Induk Kependudukan (NIK)')),
                ('education', models.CharField(choices=[(None, '=Pilih='), ('SD', 'SD'), ('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=4, verbose_name='Pendidikan Terakhir')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pekerjaan')),
                ('salary', models.PositiveIntegerField(blank=True, help_text='Diisi dengan angka', null=True, verbose_name='Penghasilan')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.PositiveIntegerField(null=True, verbose_name='No. HP')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
