# Generated by Django 3.1.4 on 2020-12-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primaseru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='no_regis',
            field=models.PositiveIntegerField(help_text='Bisa Konfirmasi Ke Bagian Pendaftaran, Contoh : 221321', verbose_name='No. Pendaftaran'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='npsn_school_origin',
            field=models.PositiveIntegerField(help_text="Bisa Cek <a href='https://referensi.data.kemdikbud.go.id/index11.php' target='_blank'><b>Disini</b></a>", verbose_name='Nomor NPSN Sekolah Asal'),
        ),
    ]
