# Generated by Django 3.1.4 on 2020-12-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primaseru', '0002_auto_20201224_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatherstudentprofile',
            name='nik',
            field=models.PositiveIntegerField(verbose_name='Nomor Induk Kependudukan (NIK)'),
        ),
        migrations.AlterField(
            model_name='motherstudentprofile',
            name='nik',
            field=models.PositiveIntegerField(verbose_name='Nomor Induk Kependudukan (NIK)'),
        ),
        migrations.AlterField(
            model_name='studentguardianprofile',
            name='nik',
            field=models.PositiveIntegerField(verbose_name='Nomor Induk Kependudukan (NIK)'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='nisn',
            field=models.PositiveIntegerField(unique=True, verbose_name='NISN'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='no_regis',
            field=models.PositiveIntegerField(help_text='Bisa Konfirmasi Ke Bagian Pendaftaran, Contoh : 221321', unique=True, verbose_name='No. Pendaftaran'),
        ),
    ]
