# Generated by Django 3.1.4 on 2021-01-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primaseru', '0002_auto_20210102_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatherstudentprofile',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='No. HP'),
        ),
        migrations.AlterField(
            model_name='motherstudentprofile',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='No. HP'),
        ),
        migrations.AlterField(
            model_name='studentguardianprofile',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='No. HP'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='handpone',
            field=models.CharField(max_length=15, null=True, verbose_name='No. HP'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_doctor',
            field=models.CharField(blank=True, help_text='Isi jika memiliki dokter keluarga dan atau dalam masa penyambuhan penyakit', max_length=15, null=True, verbose_name='No Telepon Dokter'),
        ),
    ]
