# Generated by Django 3.1.4 on 2020-12-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primaseru', '0003_auto_20201224_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='no_regis',
            field=models.PositiveIntegerField(default=0, help_text='Bisa Konfirmasi Ke Bagian Pendaftaran, Contoh : 221321', unique=True, verbose_name='No. Pendaftaran'),
        ),
    ]
