# Generated by Django 3.1.4 on 2021-01-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primaseru', '0003_auto_20210107_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
