# Generated by Django 3.1.4 on 2021-02-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primaseru', '0004_studentprofile_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nama Gelombang Pendaftaran')),
                ('start_date', models.DateField(verbose_name='Tanggal Dimulai Pendaftaran')),
                ('end_date', models.DateField(verbose_name='Tanggal Berakhir Pendaftaran')),
            ],
        ),
    ]
