# Generated by Django 3.1.4 on 2020-12-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primaseru', '0004_auto_20201224_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='handpone',
            field=models.PositiveIntegerField(default=0, verbose_name='No. HP'),
        ),
    ]
