# Generated by Django 3.1.4 on 2020-12-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primaseru', '0005_auto_20201224_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatherstudentprofile',
            name='date_born',
            field=models.DateField(null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AlterField(
            model_name='fatherstudentprofile',
            name='nik',
            field=models.PositiveIntegerField(null=True, verbose_name='Nomor Induk Kependudukan (NIK)'),
        ),
        migrations.AlterField(
            model_name='fatherstudentprofile',
            name='phone',
            field=models.PositiveIntegerField(null=True, verbose_name='No. HP'),
        ),
        migrations.AlterField(
            model_name='motherstudentprofile',
            name='date_born',
            field=models.DateField(null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AlterField(
            model_name='motherstudentprofile',
            name='nik',
            field=models.PositiveIntegerField(null=True, verbose_name='Nomor Induk Kependudukan (NIK)'),
        ),
        migrations.AlterField(
            model_name='motherstudentprofile',
            name='phone',
            field=models.PositiveIntegerField(null=True, verbose_name='No. HP'),
        ),
        migrations.AlterField(
            model_name='studentguardianprofile',
            name='date_born',
            field=models.DateField(null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AlterField(
            model_name='studentguardianprofile',
            name='nik',
            field=models.PositiveIntegerField(null=True, verbose_name='Nomor Induk Kependudukan (NIK)'),
        ),
        migrations.AlterField(
            model_name='studentguardianprofile',
            name='phone',
            field=models.PositiveIntegerField(null=True, verbose_name='No. HP'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='address_kk',
            field=models.TextField(null=True, verbose_name='Alamat KK'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_born',
            field=models.DateField(null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='handpone',
            field=models.PositiveIntegerField(null=True, verbose_name='No. HP'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='nik',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Nomor Induk Kependudukan (NIK)'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='nisn',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='NISN'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='no_kk',
            field=models.PositiveIntegerField(null=True, verbose_name='Nomor Kartu Keluarga (KK)'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='no_regis',
            field=models.PositiveIntegerField(help_text='Bisa Konfirmasi Ke Bagian Pendaftaran, Contoh : 221321', null=True, unique=True, verbose_name='No. Pendaftaran'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='npsn_school_origin',
            field=models.PositiveIntegerField(help_text="Bisa Cek <a href='https://referensi.data.kemdikbud.go.id/index11.php' target='_blank'><b>Disini</b></a>", null=True, verbose_name='Nomor NPSN Sekolah Asal'),
        ),
    ]
