# Generated by Django 3.1.4 on 2020-12-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primaseru', '0006_auto_20201224_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
    ]
