# Generated by Django 3.1.4 on 2021-03-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primaseru', '0007_auto_20210311_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='religion',
            field=models.CharField(choices=[(None, '=Pilih='), ('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katholik', 'Katholik'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Kong Hu Cu', 'Kong Hu Cu')], max_length=10, verbose_name='Agama'),
        ),
    ]
